import type {State} from '@/shared/finance';
export type AuthUser={id:string;name:string;email:string};
async function parse(response:Response):Promise<unknown>{if(!response.headers.get('content-type')?.includes('application/json'))throw Error('Não foi possível acessar sua sessão. Entre novamente ou tente mais tarde.');return response.json();}
export async function getSession():Promise<AuthUser|null>{const response=await fetch('/api/auth/session',{cache:'no-store',credentials:'same-origin'});const data=await parse(response) as {authenticated?:boolean;user?:AuthUser|null;error?:string};if(!response.ok)throw Error(data.error||'Não foi possível verificar sua sessão.');return data.authenticated?data.user??null:null;}
export async function login(email:string,password:string):Promise<AuthUser>{const response=await fetch('/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},credentials:'same-origin',body:JSON.stringify({email,password})});const data=await parse(response) as {user?:AuthUser;error?:string};if(!response.ok||!data.user)throw Error(data.error||'Não foi possível entrar.');return data.user;}
export async function register(name:string,email:string,password:string):Promise<AuthUser>{const response=await fetch('/api/auth/register',{method:'POST',headers:{'Content-Type':'application/json'},credentials:'same-origin',body:JSON.stringify({name,email,password,privacyAccepted:true})});const data=await parse(response) as {user?:AuthUser;error?:string};if(!response.ok||!data.user)throw Error(data.error||'Não foi possível criar sua conta.');return data.user;}
export async function logout():Promise<void>{const response=await fetch('/api/auth/logout',{method:'POST',credentials:'same-origin'});if(!response.ok){const data=await parse(response) as {error?:string};throw Error(data.error||'Não foi possível sair.');}}
export async function loadState():Promise<State>{const response=await fetch('/api/state',{cache:'no-store'});const data=await parse(response) as State&{error?:string};if(!response.ok)throw Error(data.error||'Não foi possível carregar seus dados.');return data;}
export async function mutate(kind:string,method:string,data:unknown,key:string,id?:string){const response=await fetch(`/api/${kind}${id?'/'+encodeURIComponent(id):''}`,{method,headers:{'Content-Type':'application/json','Idempotency-Key':key},body:method==='DELETE'?undefined:JSON.stringify(data)});const result=await parse(response) as {ok?:boolean;error?:string};if(!response.ok)throw Error(result.error||'Não foi possível salvar.');return result;}
