import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync} from 'node:fs';
import {handleApi,readState,money,addMonths,cardDue,splitAmount,balances,invoiceBalance} from '../.sites-runtime/finance-test.mjs';
function database(){const sqlite=new DatabaseSync(':memory:');sqlite.exec(readFileSync(new URL('../drizzle/0000_overjoyed_lenny_balinger.sql',import.meta.url),'utf8'));const db={prepare(sql){let params=[];const statement={bind(...p){params=p;return statement},async first(){return sqlite.prepare(sql).get(...params)||null},async all(){return {results:sqlite.prepare(sql).all(...params)}},async run(){return sqlite.prepare(sql).run(...params)}};return statement},async batch(statements){sqlite.exec('BEGIN');try{const out=[];for(const s of statements)out.push(await s.run());sqlite.exec('COMMIT');return out}catch(e){sqlite.exec('ROLLBACK');throw e}}};return {db,sqlite}}
const account={name:'Conta',kind:'checking',opening:100000,color:'#267a55',limit:0,closing:5,due:12};
function req(path,method='GET',data,owner='alice',key=crypto.randomUUID(),origin='https://finance.test'){return new Request('https://finance.test/api/'+path,{method,headers:{...(owner?{'oai-authenticated-user-id':owner}:{}),'Content-Type':'application/json','Origin':origin,'Idempotency-Key':key},body:method==='GET'||method==='DELETE'?undefined:JSON.stringify(data)})}
async function seed(db,owner='alice',data=account){const r=await handleApi(req('accounts','POST',data,owner),{DB:db});assert.equal(r.status,201);return (await readState(db,owner)).accounts.at(-1)}
test('BRL parser preserves cents and rejects excess precision',()=>{assert.equal(money('1.234,56'),123456);assert.equal(money('0,01'),1);assert.equal(money('-45,10'),-4510);assert.throws(()=>money('12,999'));assert.throws(()=>money('Infinity'));assert.throws(()=>money('1e6'))});
test('Installments preserve every cent and clamp month ends',()=>{assert.deepEqual(splitAmount(10000,3),[3334,3333,3333]);assert.equal(addMonths('2026-01-31',1),'2026-02-28');assert.equal(addMonths('2024-01-31',1),'2024-02-29');assert.equal(cardDue('2026-09-05',5,12),'2026-10-12');assert.equal(cardDue('2026-09-04',5,12),'2026-09-12');assert.equal(cardDue('2026-12-26',25,5),'2027-02-05')});
test('Missing identity is denied before any data access',async()=>{assert.equal((await handleApi(req('state','GET',undefined,''),{})).status,401)});
test('Foreign origins are rejected',async()=>{const {db}=database();assert.equal((await handleApi(req('accounts','POST',account,'alice',crypto.randomUUID(),'https://evil.test'),{DB:db})).status,403)});
test('Owner scoped reads, updates, deletes and references',async()=>{const {db}=database();const a=await seed(db);assert.equal((await readState(db,'bob')).accounts.length,0);assert.equal((await handleApi(req('accounts/'+a.id,'PUT',{...account,name:'hacked'},'bob'),{DB:db})).status,404);assert.equal((await handleApi(req('accounts/'+a.id,'DELETE',undefined,'bob'),{DB:db})).status,404);assert.equal((await handleApi(req('transactions','POST',{title:'x',amount:100,type:'expense',category:'Outros',accountId:a.id,date:'2026-09-08',status:'paid'},'bob'),{DB:db})).status,400)});
test('Idempotency keys prevent duplicate records',async()=>{const {db}=database();const key=crypto.randomUUID();assert.equal((await handleApi(req('accounts','POST',account,'alice',key),{DB:db})).status,201);assert.equal((await handleApi(req('accounts','POST',account,'alice',key),{DB:db})).status,200);assert.equal((await readState(db,'alice')).accounts.length,1)});
test('Credit installments are atomic, payments are not new expenses',async()=>{const {db}=database();const cash=await seed(db);const card=await seed(db,'alice',{...account,name:'Cartão',kind:'credit',opening:0});const buy={title:'Compra',amount:10000,type:'expense',category:'Compras',accountId:card.id,date:'2026-09-04',status:'pending',installments:3};assert.equal((await handleApi(req('transactions','POST',buy),{DB:db})).status,201);let s=await readState(db,'alice');assert.equal(s.transactions.length,3);assert.equal(s.transactions.reduce((n,t)=>n+t.amount,0),10000);assert.deepEqual(s.transactions.map(t=>t.date).sort(),['2026-09-12','2026-10-12','2026-11-12']);const payment={title:'Fatura',amount:3334,type:'transfer',category:'Transferência',accountId:cash.id,toId:card.id,date:'2026-10-01',invoiceMonth:'2026-09',status:'paid'};assert.equal((await handleApi(req('transactions','POST',payment),{DB:db})).status,201);s=await readState(db,'alice');assert.equal(invoiceBalance(s,card.id,'2026-09'),0);assert.equal(invoiceBalance(s,card.id,'2026-10'),3333);const b=balances(s,'2026-10-01');assert.equal(b[cash.id],96666);assert.equal(b[card.id],-6666);assert.equal(s.transactions.filter(t=>t.type==='expense').reduce((n,t)=>n+t.amount,0),10000)});
test('Pending cash expenses do not debit the bank, delete preserves references',async()=>{const {db}=database();const a=await seed(db);const t={title:'Aluguel',amount:12000,type:'expense',category:'Moradia',accountId:a.id,date:'2026-09-08',status:'pending'};assert.equal((await handleApi(req('transactions','POST',t),{DB:db})).status,201);const s=await readState(db,'alice');assert.equal(balances(s,'2026-09-08')[a.id],100000);assert.equal((await handleApi(req('accounts/'+a.id,'DELETE'),{DB:db})).status,409)});
test('Invalid dates, fractional cents and unknown fields rejected',async()=>{const {db}=database();const a=await seed(db);for(const change of [{date:'2026-02-30'},{amount:1.1},{owner:'bob'},{amount:-1}]){const t={title:'Teste',amount:100,type:'expense',category:'Outros',accountId:a.id,date:'2026-09-08',status:'paid',...change};assert.equal((await handleApi(req('transactions','POST',t),{DB:db})).status,400)}assert.equal((await readState(db,'alice')).transactions.length,0)});
test('Payload size is bounded even without content-length',async()=>{const {db}=database();assert.equal((await handleApi(req('accounts','POST',{...account,name:'a'.repeat(18000)}),{DB:db})).status,413)});
test('Literal SQL-like input stays data',async()=>{const {db}=database();await seed(db,'alice',{...account,name:"'; DROP TABLE finance_records; --"});assert.equal((await readState(db,'alice')).accounts[0].name,"'; DROP TABLE finance_records; --")});
