import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {createHash} from 'node:crypto';
import {readFileSync} from 'node:fs';
import {handleApi,readState,money,brl,addMonths,cardDue,splitAmount,balances,invoiceBalance,creditCardInvoiceSummary,today,isBusinessDay,scheduledIncomeDate} from '../.sites-runtime/finance-test.mjs';
const account={name:'Conta',kind:'checking',opening:100000,color:'#267a55',limit:0,closing:5,due:12};
const fixtureTokens={alice:'fixture-session-alice',bob:'fixture-session-bob'};
function fixtureCookie(owner){return owner?`clareza_session=${fixtureTokens[owner]}`:''}
function req(path,method='GET',data,owner='alice',key=crypto.randomUUID(),origin='https://finance.test'){return new Request('https://finance.test/api/'+path,{method,headers:{...(owner?{Cookie:fixtureCookie(owner)}:{}),'Content-Type':'application/json','Origin':origin,'Idempotency-Key':key},body:method==='GET'||method==='DELETE'?undefined:JSON.stringify(data)})}
function authReq(path,method='POST',data,cookie=''){return new Request('https://finance.test/api/'+path,{method,headers:{'Content-Type':'application/json','Origin':'https://finance.test',...(cookie?{Cookie:cookie}:{})},body:method==='GET'?undefined:JSON.stringify(data)})}
function seedFixtureUsers(sqlite){const now=Date.now();for(const [owner,token] of Object.entries(fixtureTokens)){sqlite.prepare('INSERT INTO app_users (id,email,name,password_hash,password_salt,password_iterations,created) VALUES (?,?,?,?,?,?,?)').run(owner,`${owner}@fixture.test`,owner,'fixture-hash','fixture-salt',1,now);sqlite.prepare('INSERT INTO app_sessions (id,user_id,token_hash,created,expires) VALUES (?,?,?,?,?)').run(`session-${owner}`,owner,createHash('sha256').update(token).digest('hex'),now,now+86400000)}}
function database(){const sqlite=new DatabaseSync(':memory:');sqlite.exec(readFileSync(new URL('../drizzle/0000_overjoyed_lenny_balinger.sql',import.meta.url),'utf8'));sqlite.exec(readFileSync(new URL('../drizzle/0001_add_app_auth.sql',import.meta.url),'utf8'));sqlite.exec(readFileSync(new URL('../drizzle/0002_store_idempotency_results.sql',import.meta.url),'utf8'));seedFixtureUsers(sqlite);const db={prepare(sql){let params=[];const statement={bind(...p){params=p;return statement},async first(){return sqlite.prepare(sql).get(...params)||null},async all(){return {results:sqlite.prepare(sql).all(...params)}},async run(){return sqlite.prepare(sql).run(...params)}};return statement},async batch(statements){sqlite.exec('BEGIN');try{const out=[];for(const s of statements)out.push(await s.run());sqlite.exec('COMMIT');return out}catch(e){sqlite.exec('ROLLBACK');throw e}}};return {db,sqlite}}
async function seed(db,owner='alice',data=account){const r=await handleApi(req('accounts','POST',data,owner),{DB:db});assert.equal(r.status,201);return (await readState(db,owner)).accounts.at(-1)}
test('BRL parser preserves cents and rejects excess precision',()=>{assert.equal(money('1.234,56'),123456);assert.equal(money('0,01'),1);assert.equal(money('-45,10'),-4510);assert.throws(()=>money('12,999'));assert.throws(()=>money('Infinity'));assert.throws(()=>money('1e6'))});
test('BRL formatter receives cent values without scaling them twice',()=>{assert.match(brl(57298),/572,98/);assert.match(brl(2491),/24,91/)});
test('Installments preserve every cent and clamp month ends',()=>{assert.deepEqual(splitAmount(10000,3),[3334,3333,3333]);assert.equal(addMonths('2026-01-31',1),'2026-02-28');assert.equal(addMonths('2024-01-31',1),'2024-02-29');assert.equal(cardDue('2026-09-05',5,12),'2026-10-12');assert.equal(cardDue('2026-09-04',5,12),'2026-09-12');assert.equal(cardDue('2026-12-26',25,5),'2027-02-05')});
test('Missing identity is denied before any data access',async()=>{assert.equal((await handleApi(req('state','GET',undefined,''),{})).status,401)});
test('Account registration and login work with Cloudflare-compatible password hashing',async()=>{const {db,sqlite}=database();const credentials={name:'Maria Clareza',email:'Maria@Example.com',password:'senha-segura-123',privacyAccepted:true};const registered=await handleApi(authReq('auth/register','POST',credentials),{DB:db});assert.equal(registered.status,201);const stored=sqlite.prepare('SELECT email, password_iterations FROM app_users WHERE email = ?').get('maria@example.com');assert.equal(stored.email,'maria@example.com');assert.equal(stored.password_iterations,100000);const cookie=registered.headers.get('set-cookie');assert.match(cookie,/clareza_session=.*HttpOnly/);const session=await handleApi(authReq('auth/session','GET',undefined,cookie),{DB:db});assert.equal(session.status,200);assert.equal((await session.json()).authenticated,true);assert.equal((await handleApi(authReq('auth/login','POST',{email:'maria@example.com',password:'senha-segura-123'}),{DB:db})).status,200);assert.equal((await handleApi(authReq('auth/login','POST',{email:'maria@example.com',password:'errada'}),{DB:db})).status,401)});
test('Foreign origins are rejected',async()=>{const {db}=database();assert.equal((await handleApi(req('accounts','POST',account,'alice',crypto.randomUUID(),'https://evil.test'),{DB:db})).status,403)});
test('Owner scoped reads, updates, deletes and references',async()=>{const {db}=database();const a=await seed(db);assert.equal((await readState(db,'bob')).accounts.length,0);assert.equal((await handleApi(req('accounts/'+a.id,'PUT',{...account,name:'hacked'},'bob'),{DB:db})).status,404);assert.equal((await handleApi(req('accounts/'+a.id,'DELETE',undefined,'bob'),{DB:db})).status,404);assert.equal((await handleApi(req('transactions','POST',{title:'x',amount:100,type:'expense',category:'Outros',accountId:a.id,date:'2026-09-08',status:'paid'},'bob'),{DB:db})).status,400)});
test('Non-transfer records cannot reference a destination account',async()=>{const {db}=database();const source=await seed(db);const destination=await seed(db,'alice',{...account,name:'Destino'});const response=await handleApi(req('transactions','POST',{title:'Despesa',amount:100,type:'expense',category:'Outros',accountId:source.id,toId:destination.id,date:'2026-09-08',status:'paid'},'alice'),{DB:db});assert.equal(response.status,400);assert.equal((await readState(db,'alice')).transactions.length,0)});
test('Editing and deleting preserve the persisted centavo value',async()=>{const {db}=database();const a=await seed(db);const created=await handleApi(req('transactions','POST',{title:'Café',amount:12345,type:'expense',category:'Outros',accountId:a.id,date:'2026-09-08',status:'paid'},'alice'),{DB:db});assert.equal(created.status,201);const id=(await created.json()).id;const edited=await handleApi(req('transactions/'+id,'PUT',{title:'Café grande',amount:12346,type:'expense',category:'Outros',accountId:a.id,date:'2026-09-08',status:'paid',installments:1},'alice'),{DB:db});assert.equal(edited.status,200);assert.equal((await readState(db,'alice')).transactions[0].amount,12346);assert.equal((await handleApi(req('transactions/'+id,'DELETE',undefined,'alice'),{DB:db})).status,200);assert.equal((await readState(db,'alice')).transactions.length,0)});
test('Idempotency keys replay the original response and reject reuse',async()=>{const {db}=database();const key=crypto.randomUUID();const first=await handleApi(req('accounts','POST',account,'alice',key),{DB:db});assert.equal(first.status,201);const firstBody=await first.json();const replay=await handleApi(req('accounts','POST',account,'alice',key),{DB:db});assert.equal(replay.status,201);assert.deepEqual(await replay.json(),firstBody);assert.equal((await handleApi(req('accounts','POST',{...account,name:'Outra'},'alice',key),{DB:db})).status,409);assert.equal((await readState(db,'alice')).accounts.length,1)});
test('Onboarding validates before writing and is atomic and replayable',async()=>{const {db}=database();const key=crypto.randomUUID();const invalid={account:{...account},goal:{name:'Reserva',target:0,saved:0,date:'2027-01-01',color:'#5376d9'}};assert.equal((await handleApi(req('onboarding','POST',invalid,'alice',key),{DB:db})).status,400);assert.equal((await readState(db,'alice')).accounts.length,0);const payload={account:{...account,name:'Conta inicial',opening:57298},income:{title:'Renda mensal',amount:250000,startMonth:'2026-09',active:false,automatic:false,businessDayRule:'previous_business_day'},goal:{name:'Reserva',target:1000000,saved:0,date:'2027-01-01',color:'#5376d9'}};const first=await handleApi(req('onboarding','POST',payload,'alice',key),{DB:db});assert.equal(first.status,201);const response=await first.json();const replay=await handleApi(req('onboarding','POST',payload,'alice',key),{DB:db});assert.equal(replay.status,201);assert.deepEqual(await replay.json(),response);const state=await readState(db,'alice');assert.equal(state.accounts.length,1);assert.equal(state.incomePlans.length,1);assert.equal(state.goals.length,1);assert.equal(state.accounts[0].opening,57298);assert.equal(state.incomePlans[0].amount,250000);assert.equal((await handleApi(req('onboarding','POST',{...payload,account:{...payload.account,name:'Outra'}},'alice',key),{DB:db})).status,409)});
test('Credit installments are atomic, payments are not new expenses',async()=>{const {db}=database();const cash=await seed(db);const card=await seed(db,'alice',{...account,name:'Cartão',kind:'credit',opening:0});const buy={title:'Compra',amount:10000,type:'expense',category:'Compras',accountId:card.id,date:'2026-09-04',status:'pending',installments:3};assert.equal((await handleApi(req('transactions','POST',buy),{DB:db})).status,201);let s=await readState(db,'alice');assert.equal(s.transactions.length,3);assert.equal(s.transactions.reduce((n,t)=>n+t.amount,0),10000);assert.deepEqual(s.transactions.map(t=>t.date).sort(),['2026-09-12','2026-10-12','2026-11-12']);const payment={title:'Fatura',amount:3334,type:'transfer',category:'Transferência',accountId:cash.id,toId:card.id,date:'2026-10-01',invoiceMonth:'2026-09',status:'paid'};assert.equal((await handleApi(req('transactions','POST',payment),{DB:db})).status,201);s=await readState(db,'alice');assert.equal(invoiceBalance(s,card.id,'2026-09'),0);assert.equal(invoiceBalance(s,card.id,'2026-10'),3333);const b=balances(s,'2026-10-01');assert.equal(b[cash.id],96666);assert.equal(b[card.id],-6666);assert.equal(s.transactions.filter(t=>t.type==='expense').reduce((n,t)=>n+t.amount,0),10000)});
test('Card invoice summary keeps spending visible after payment and separates future commitments',()=>{
  const state={accounts:[],transactions:[
    {id:'aug-a',title:'Mercado',amount:12000,type:'expense',category:'Alimenta\u00e7\u00e3o',accountId:'card',date:'2026-08-12',status:'pending'},
    {id:'aug-pay',title:'Pagamento agosto',amount:12000,type:'transfer',category:'Transfer\u00eancia',accountId:'bank',toId:'card',invoiceMonth:'2026-08',date:'2026-09-01',status:'paid'},
    {id:'sep-a',title:'Mercado',amount:10000,type:'expense',category:'Alimenta\u00e7\u00e3o',accountId:'card',date:'2026-09-12',status:'pending'},
    {id:'sep-h',title:'Farm\u00e1cia',amount:5000,type:'expense',category:'Sa\u00fade',accountId:'card',date:'2026-09-12',status:'pending'},
    {id:'sep-pay',title:'Pagamento setembro',amount:15000,type:'transfer',category:'Transfer\u00eancia',accountId:'bank',toId:'card',invoiceMonth:'2026-09',date:'2026-09-20',status:'paid'},
    {id:'oct-a',title:'Parcela',amount:4000,type:'expense',category:'Compras',accountId:'card',date:'2026-10-12',status:'pending'},
    {id:'oct-pay',title:'Pagamento adiantado',amount:1000,type:'transfer',category:'Transfer\u00eancia',accountId:'bank',toId:'card',invoiceMonth:'2026-10',date:'2026-10-01',status:'paid'},
    {id:'nov-a',title:'Parcela',amount:2500,type:'expense',category:'Compras',accountId:'card',date:'2026-11-12',status:'pending'},
  ],budgets:[],goals:[],recurrences:[],incomePlans:[],categories:[],tags:[]};
  const summary=creditCardInvoiceSummary(state,'card','2026-09');
  assert.equal(summary.spent,15000);
  assert.equal(summary.paid,15000);
  assert.equal(summary.outstanding,0);
  assert.equal(invoiceBalance(state,'card','2026-09'),0);
  assert.equal(summary.previousSpent,12000);
  assert.equal(summary.change,3000);
  assert.equal(summary.futureCommitted,5500);
  assert.deepEqual(summary.upcomingInvoices.map(invoice=>invoice.month),['2026-10','2026-11']);
  assert.deepEqual(summary.topCategory,{name:'Alimenta\u00e7\u00e3o',amount:10000});
});
test('Card invoice summary compares across year boundaries',()=>{
  const state={accounts:[],transactions:[
    {id:'dec-a',title:'Compra',amount:700,type:'expense',category:'Outros',accountId:'card',date:'2025-12-12',status:'pending'},
    {id:'jan-a',title:'Compra',amount:900,type:'expense',category:'Outros',accountId:'card',date:'2026-01-12',status:'pending'},
  ],budgets:[],goals:[],recurrences:[],incomePlans:[],categories:[],tags:[]};
  assert.equal(creditCardInvoiceSummary(state,'card','2026-01').previousSpent,700);
});
test('Personal card target is optional, persisted, and validated',async()=>{
  const {db}=database();
  const card=await seed(db,'alice',{...account,name:'Cart\u00e3o meta',kind:'credit',monthlyTarget:180000});
  assert.equal(card.monthlyTarget,180000);
  assert.equal((await handleApi(req('accounts','POST',{...account,name:'Meta inv\u00e1lida',kind:'credit',monthlyTarget:-1}),{DB:db})).status,400);
  assert.equal((await handleApi(req('accounts','POST',{...account,name:'Cart\u00e3o sem meta',kind:'credit'}),{DB:db})).status,201);
});
test('Pending cash expenses do not debit the bank, delete preserves references',async()=>{const {db}=database();const a=await seed(db);const t={title:'Aluguel',amount:12000,type:'expense',category:'Moradia',accountId:a.id,date:'2026-09-08',status:'pending'};assert.equal((await handleApi(req('transactions','POST',t),{DB:db})).status,201);const s=await readState(db,'alice');assert.equal(balances(s,'2026-09-08')[a.id],100000);assert.equal((await handleApi(req('accounts/'+a.id,'DELETE'),{DB:db})).status,409)});
test('Invalid dates, fractional cents and unknown fields rejected',async()=>{const {db}=database();const a=await seed(db);for(const change of [{date:'2026-02-30'},{amount:1.1},{owner:'bob'},{amount:-1}]){const t={title:'Teste',amount:100,type:'expense',category:'Outros',accountId:a.id,date:'2026-09-08',status:'paid',...change};assert.equal((await handleApi(req('transactions','POST',t),{DB:db})).status,400)}assert.equal((await readState(db,'alice')).transactions.length,0)});
test('Payload size is bounded even without content-length',async()=>{const {db}=database();assert.equal((await handleApi(req('accounts','POST',{...account,name:'a'.repeat(18000)}),{DB:db})).status,413)});
test('Literal SQL-like input stays data',async()=>{const {db}=database();await seed(db,'alice',{...account,name:"'; DROP TABLE finance_records; --"});assert.equal((await readState(db,'alice')).accounts[0].name,"'; DROP TABLE finance_records; --")});
test('Custom categories and tags can be attached to transactions',async()=>{const {db}=database();const a=await seed(db);const categoryResponse=await handleApi(req('categories','POST',{name:'Pets',type:'expense',color:'#267a55'},'alice'),{DB:db});assert.equal(categoryResponse.status,201);const categoryId=(await categoryResponse.json()).id;const subcategoryResponse=await handleApi(req('categories','POST',{name:'Veterinário',type:'expense',parentId:categoryId,color:'#5376d9'},'alice'),{DB:db});assert.equal(subcategoryResponse.status,201);const tagResponse=await handleApi(req('tags','POST',{name:'Casa',color:'#e5a04d'},'alice'),{DB:db});assert.equal(tagResponse.status,201);const tagId=(await tagResponse.json()).id;const transaction={title:'Consulta',amount:25000,type:'expense',category:'Pets',subcategory:'Veterinário',tags:[tagId],accountId:a.id,date:'2026-09-08',status:'paid'};assert.equal((await handleApi(req('transactions','POST',transaction,'alice'),{DB:db})).status,201);const state=await readState(db,'alice');assert.equal(state.categories.length,2);assert.equal(state.tags.length,1);assert.deepEqual(state.transactions[0].tags,[tagId]);assert.equal(state.transactions[0].subcategory,'Veterinário')});
test('Due recurring records generate one transaction and advance safely',async()=>{const {db}=database();const a=await seed(db);const recurrence={title:'Aluguel',amount:120000,type:'expense',category:'Moradia',accountId:a.id,startDate:today(),nextDate:today(),frequency:'monthly',active:true};assert.equal((await handleApi(req('recurrences','POST',recurrence,'alice'),{DB:db})).status,201);let response=await handleApi(req('state','GET',undefined,'alice'),{DB:db});assert.equal(response.status,200);let state=await response.json();assert.equal(state.transactions.length,1);assert.equal(state.recurrences.length,1);assert.notEqual(state.recurrences[0].nextDate,today());response=await handleApi(req('state','GET',undefined,'alice'),{DB:db});state=await response.json();assert.equal(state.transactions.length,1);assert.equal(state.recurrences.length,1)});
test('Income planning does not alter the opening balance',async()=>{const {db}=database();const a=await seed(db,'alice',{...account,opening:57298});const plan={title:'Renda mensal',amount:57298,startMonth:today().slice(0,7),active:false,automatic:false,businessDayRule:'previous_business_day'};assert.equal((await handleApi(req('incomePlans','POST',plan,'alice'),{DB:db})).status,201);const state=await readState(db,'alice');assert.equal(state.incomePlans.length,1);assert.equal(state.transactions.length,0);assert.equal(balances(state)[a.id],57298)});
test('Income scheduling moves weekends and holidays to the previous business day',()=>{assert.equal(isBusinessDay('2026-09-04'),true);assert.equal(scheduledIncomeDate('2026-09',5),'2026-09-04');assert.equal(scheduledIncomeDate('2026-09',7),'2026-09-04');assert.equal(scheduledIncomeDate('2026-11',15),'2026-11-13')});
test('Automatic income generates a paid entry once and advances the plan',async()=>{const {db}=database();const a=await seed(db);const previousMonth=addMonths(`${today().slice(0,7)}-01`,-1).slice(0,7);const plan={title:'Salário',amount:250000,accountId:a.id,dayOfMonth:5,startMonth:previousMonth,nextPeriod:previousMonth,active:true,automatic:true,businessDayRule:'previous_business_day'};assert.equal((await handleApi(req('incomePlans','POST',plan,'alice'),{DB:db})).status,201);let response=await handleApi(req('state','GET',undefined,'alice'),{DB:db});assert.equal(response.status,200);let state=await response.json();const generated=state.transactions.filter(t=>t.incomePlanId);assert.ok(generated.length>=1);assert.ok(generated.every(t=>t.type==='income'&&t.status==='paid'));assert.equal(generated[0].date,scheduledIncomeDate(previousMonth,5));assert.ok(state.incomePlans[0].nextDate>today());const balanceAfterFirstRead=balances(state)[a.id];response=await handleApi(req('state','GET',undefined,'alice'),{DB:db});state=await response.json();assert.equal(state.transactions.filter(t=>t.incomePlanId).length,generated.length);assert.equal(balances(state)[a.id],balanceAfterFirstRead)});
test('Automatic income keeps the destination account referenced',async()=>{const {db}=database();const a=await seed(db);const plan={title:'Pró-labore',amount:100000,accountId:a.id,dayOfMonth:1,startMonth:'2026-01',nextPeriod:'2026-01',active:true,automatic:true,businessDayRule:'previous_business_day'};assert.equal((await handleApi(req('incomePlans','POST',plan,'alice'),{DB:db})).status,201);const created=await readState(db,'alice');assert.equal((await handleApi(req('accounts/'+a.id,'DELETE',undefined,'alice'),{DB:db})).status,409);assert.equal(created.incomePlans[0].accountId,a.id)});
test('Cookie sessions are revoked and spoofed identity headers are ignored',async()=>{const {db}=database();const registered=await handleApi(authReq('auth/register','POST',{name:'Sessão de teste',email:'session@example.test',password:'senha-segura-123',privacyAccepted:true}),{DB:db});assert.equal(registered.status,201);const cookie=registered.headers.get('set-cookie').split(';')[0];assert.equal((await handleApi(authReq('auth/session','GET',undefined,cookie),{DB:db})).status,200);assert.equal((await handleApi(authReq('auth/logout','POST',undefined,cookie),{DB:db})).status,200);const afterLogout=await handleApi(authReq('auth/session','GET',undefined,cookie),{DB:db});assert.equal((await afterLogout.json()).authenticated,false);const spoofed=new Request('https://finance.test/api/state',{headers:{Origin:'https://finance.test','oai-authenticated-user-id':'alice',Authorization:'Bearer alice'}});assert.equal((await handleApi(spoofed,{DB:db})).status,401)});
test('Generated income occurrences accept encoded IDs and keep their plan link',async()=>{
  const {db,sqlite}=database();
  const a=await seed(db);
  const planId=crypto.randomUUID();
  const transactionId=`income-plan:${planId}:2026-09`;
  const original={title:'Renda mensal',amount:191800,type:'income',category:'Sal\u00e1rio',accountId:a.id,date:'2026-09-04',status:'paid',installments:1,incomePlanId:planId,incomePeriod:'2026-09'};
  sqlite.prepare('INSERT INTO finance_records (id, owner, kind, data, created) VALUES (?, ?, ?, ?, ?)').run(transactionId,'alice','transactions',JSON.stringify(original),Date.now());
  const updated={title:'Renda mensal',amount:191800,type:'income',category:'Sal\u00e1rio',accountId:a.id,date:'2026-10-05',status:'pending',installments:1};
  const edited=await handleApi(req('transactions/'+encodeURIComponent(transactionId),'PUT',updated,'alice'),{DB:db});
  assert.equal(edited.status,200);
  let stored=(await readState(db,'alice')).transactions.find(t=>t.id===transactionId);
  assert.equal(stored.date,'2026-10-05');
  assert.equal(stored.status,'pending');
  assert.equal(stored.incomePlanId,planId);
  assert.equal(stored.incomePeriod,'2026-09');
  assert.equal((await handleApi(req('transactions/'+encodeURIComponent(transactionId),'DELETE',undefined,'alice'),{DB:db})).status,200);
  stored=(await readState(db,'alice')).transactions.find(t=>t.id===transactionId);
  assert.equal(stored,undefined);
});
test('Public authentication attempts are rate limited before password verification',async()=>{const {db}=database();const request=()=>new Request('https://finance.test/api/auth/login',{method:'POST',headers:{Origin:'https://finance.test','Content-Type':'application/json','CF-Connecting-IP':'phase2-rate-limit'},body:JSON.stringify({email:'missing@example.test',password:'wrong-password'})});for(let i=0;i<30;i++)assert.notEqual((await handleApi(request(),{DB:db})).status,429);assert.equal((await handleApi(request(),{DB:db})).status,429)});
